### ISSUE TITLE
Keychain cannot be found

### ISSUE THREAD

**Issue by chrism9876** [jamf/NoMADLogin-AD#2]
When logging in to a mac that hasnt been logged in to before by that user. I get an error. A keychain cannot be found to store USERNAME@DOMAIN.

I am using the following prefrences

Create keychain = true
Add nomad to keychain = true
Reset keychain if password doesnt match = true

If i remove add nomad to keychain i can login but have no keychain

If i then run
Chmod 777 /Users/USERNAME/Library/Keychains

And enable add nomad to keychain

Then logout and backin. A keychain is created.

The premissions on the keychain folder before was USERNAME:staff rwx--x--x or 711

Tested on 12.2 1 and 11.6.4

If i manually create the folder it works
Sudo mkdir /Users/USERNAME
sudo chown USERNAME /Users/USERNAME

**Comment by 07-C9** [comment]
I have a shared lab using Nomad where this just started happening as well, seemingly at random. But it doesn't seem to be happening at other buildings with the exact same setup. Did you ever find out what this is? There's not much official Nomad support at this point.

**Comment by chrism9876** [comment]
No i gave up couldnt get it to work reliably shame as when it works its good
________________________________

**Comment by 07-C9** [comment]
That's a shame. We're getting the same error, but it seems our issue is the opposite - new people are logging in fine, it's users with existing accounts that have this problem happen. Supposedly upgrading one of the computers to Monterey fixed it, but can't 100% confirm. Again, just strange as we have multiple other labs with identical setups, but this is the only one where it's happening.
